### ISSUE TITLE
Organize Classes into separate files

### ISSUE THREAD

**Issue by lindblomjd** [amschmidt2/2022-Taft-Robot#3]
It is useful to create separate classes in their own files.  This helps organize the code and makes Robot.java much more readable.

**Comment by anfroholic** [comment]
Thank you for the input. Keeping them in a single document was a conscious decision I made for some form of simplicity.  We really only have one programmer and this is their first program.  
With a single document, we can obfuscate problems like circular dependencies and couple things as tightly as we choose.  I know full well how bad this is in practice, and I've stated this quite a few times, but we're still hitting on some pretty advanced topics. Creation and manipulation of complex objects, data gathering, data processing, passing data amongst objects, control theory, hardware manipulation. 
I'm trying my best to tackle these core fundamentals without letting the language or paradigms get in the way.  Besides, we're having a lot of fun coding this and I think that counts for something. 

Thank you for your advise, I always welcome constructive criticism and thank you for helping the team. 

p.s. Apologies for the long winded response, I am also sharing this with the student
